### ISSUE TITLE
[core][ssr] Vue.use is not a function

### ISSUE THREAD

**Issue by jerakode** [vuematerial/vue-material#820]
Does it work with SSR? I can't set it with Nuxt.

1. Create plugin

```
var Vue = require('vue')
var VueMaterial = require('vue-material')

Vue.use(VueMaterial)
```
2. In `nuxt.config`
```
  plugins: [
    {src: '~plugins/vm', ssr: false}
  ]
```
3. Add CSS
4. `<md-button class="md-primary">Primary</md-button>` in markup
5. Got error
```
[nuxt.js] Cannot load components TypeError: Vue.use is not a function
```

**Comment by zapping** [comment]
SSR is being tracked in #243

**Comment by jerakode** [comment]
Not sure is this is SSR related.

**Comment by iamdubx** [comment]
So it doesn't work with Nuxt?

**Comment by pablohpsilva** [comment]
@iamdubx The error doesn't seems to be related with SSR, like @jerakode said.
We are working on vue-material 1.0 and we have a whole sprint just to make sure it works with SSR though.

**Comment by iamdubx** [comment]
@pablohpsilva this is great news. 1.0 sounds very exciting!
