### ISSUE TITLE
default.a.material.registerTheme is not a function after migrating to 1.0.0

### ISSUE THREAD

**Issue by baristaGeek** [vuematerial/vue-material#1569]
I upgraded to the latest version and changed what's suggested in this [migration guide](https://github.com/vuematerial/vue-material/issues/1189) 

I couldn't find a complete migration guide. Any suggestions?

![screen shot 2018-03-01 at 5 57 51 pm](https://user-images.githubusercontent.com/8325094/36874494-1c61d968-1d7a-11e8-9bb9-2ad498528d47.png)

**Comment by Samuell1** [comment]
Hey, just follow this https://vuematerial.io/themes/configuration/ to make themes. Now is old javascript code not needed.
